version: "3"

services:
    www:
        image: ijakab0/cats-lv5
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        links:
            - db
        networks:
            - default
        environment:
            DB_HOST: db
            DB_NAME: ferit
            DB_USER: user
            DB_PASS: test
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ferit
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    dbdata:
